### ISSUE TITLE
Појавување на C++14 errors при користење на Clang на Windows

### ISSUE THREAD

**Issue by limepixl** [joksim/OpenGLPrj#1]
Добар ден професоре.

Поради некоја причина добивам многу errors при компајлирање на проектот со CMake со понови верзии на Clang на Windows 10. Специфично C++14 errors и користејќи Clang 10.0.0+ верзии (нативните, не clang-cl пакетот на Visual Studio). Менување на -std=c++11 во -std=c++14 ги поправа сите errors. 

Поради некоја причина, Clang на многу дистрибуции на Linux не ги покажуваат овие errors и исто така GCC и MSVC не ги покажуваат. Веќе споменавте на аудиториските вежби дека најдобро е да користиме Visual Studio на Windows или GCC на Linux, со што се избегнува проблемот. Но мислев дека би било пожелно да ве известам за секој случај.

Спецификациите со кои добивам errors се: користејќи CMake на Windows 10 со Ninja build system (бидејќи само вака може да се користи Clang native на Windows). 
Минимална Clang верзија за Windows 10: [(линк до download)](https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe)

Чекори за повторување: 
- `cmake -G "Ninja" .`
- `ninja`
- Резултат: https://pastebin.com/A1WVFcRq

Решение: Користење на C++14 стандардот во CMake, со што само има output на неколку некритични warnings.

**Comment by joksim** [comment]
Здраво,

Можеш соодветно да видиш и да ги додадеш како flags кога се користи clang.

Јас тестирав со gcc и MSVC и clang не стигнав да го теститирам.

Pull Request е добредојден :)

**Comment by limepixl** [comment]
Здраво професоре,
Ги направив соодветните поправки и ги испробав, и работат со сите компајлери кои ги спомнав погоре. 
Сега околу pull request-от, мислам дека бидејќи ги сменив сите гранки, ќе бидат потребни повеќе pull requests.
Во секој од нив е сменет само еден фајл и сите измени се исти но сепак GitHub нема функционалност да спои pull requests за различни гранки.
Однапред се извинувам за спамот :)
